### PR TITLE
fix: respect Setting > Editor > General > Scrolling

### PR DESCRIPTION
**Pull request by Alexsey**
This would add support for "Prefer moving caret line to minimize editor scrolling" setting

Details: https://github.com/andreycizov/idea-partialnav/issues/3

### CODE REVIEW

**Comment by andreycizov** [comment]
Hey - thanks for submitting this. I'll check whether this works on Sunday and add this to the JetBrains repository.

If I don't do that earlier feel free to remind me.

**Comment by Alexsey** [comment]
Hey, as you said, reminding you about the PR :)

**Comment by andreycizov** [comment]
I'm going to do this today!

**Comment by andreycizov** [comment]
@Alexsey would you like to be added to CONTRIBUTORS btw?

**Pull request merged**
